### ISSUE TITLE
Token vision resetting to 0

### ISSUE THREAD

**Issue by amcvfx** [kandashi/Active-Token-Lighting#43]
I'm having an issue with Token vision settings on linked tokens resetting to zero while using ATL, CUB and MidiQOL. When a character has an effect applied that uses an ATL flag for dimSight (like Eyes of the Night for the Twilight cleric, or Googles of Night) any other effects that are applied or removed from that character seem to reset the dimSight to zero. 
The issue occurs when these modules are active:
- Active Token Lighting
- Combat Utility Belt
- Libsettings
- MidiQOL
- Dynamic Effects use Active Effects

**Comment by kandashi** [comment]
Does the Prototype Token settings of the actor have a dimSight of 0 ?

**Comment by amcvfx** [comment]
Yes those are characters with dimSight 0 by default

**Comment by kandashi** [comment]
Oh you mean non ATL effects cause a reset to 0 ?

**Comment by amcvfx** [comment]
Yes non ATL effects. Any effect that is toggled on the character resets the dimSight to 0.

**Comment by kandashi** [comment]
I can only replicate this when *deleteing* an active effect, not toggle or creation, can you confirm this?

**Comment by amcvfx** [comment]
I tried it again and it does still seem to happen when applying and removing other active effects

**Comment by kandashi** [comment]
what other modules that interact with active effects do you have enabled?

**Comment by amcvfx** [comment]
These are all the modules active (I tested them with Find the Culprit):

Active Token Lighting
Combat Utility Belt
Libsettings
MidiQOL
Dynamic Effects use Active Effects

**Comment by RavenknightDM** [comment]
We've noticed the same issue. Removing a (none-ATL) effect from a linked token will remove the light on the character. Non-linked characters are fine.

**Comment by kandashi** [comment]
This should be fixed in https://github.com/kandashi/Active-Token-Lighting/tree/0.2.12, if anyone can test to confirm that its fixed that would be great.

**Comment by RavenknightDM** [comment]
> This should be fixed in https://github.com/kandashi/Active-Token-Lighting/tree/0.2.12, if anyone can test to confirm that its fixed that would be great.

Will test it once I get back from work. Thanks Kandashi.

**Comment by RavenknightDM** [comment]
Hiya, Kandashi.
I've installed the 0.2.12 version but I still get the same error.
